export const CURRENCIES = {
  USD: 'United States dollar (USD)',
  EUR: 'Euro (EUR)',
  JPY: 'Japanese yen (JPY)',
  BGN: 'Bulgarian lev (BGN)',
  CZK: 'Czech koruna (CZK)',
  GBP: 'Pound sterling (GBP)',
  HUF: 'Hungarian forint (HUF)',
  PLN: 'Polish zloty (PLN)',
  RON: 'Romanian leu (RON)',
  SEK: 'Swedish krona (SEK)',
  CHF: 'Swiss franc (CHF)',
  ISK: 'Icelandic krona (ISK)',
  NOK: 'Norwegian krone (NOK)',
  HRK: 'Croatian kuna (HRK)',
  RUB: 'Russian rouble (RUB)',
  TRY: 'Turkish lira (TRY)',
  AUD: 'Australian dollar (AUD)',
}
export const SYMBOL = {
  USD: '$',
  EUR: '€',
  JPY: '¥',
  BGN: 'лв.',
  CZK: 'Kč',
  GBP: '£',
  HUF: 'Ft',
  PLN: 'zł',
  RON: 'L',
  SEK: 'kr',
  CHF: 'Fr',
  ISK: 'kr',
  NOK: 'kr',
  HRK: 'kn',
  RUB: '₽',
  TRY: '₺',
  AUD: 'A$',
}

export const CURRENCY_OPTIONS = [
  { label: 'United States dollar (USD)', value: 'USD' },
  { label: 'Euro (EUR)', value: 'EUR' },
  { label: 'Japanese yen (JPY)', value: 'JPY' },
  { label: 'Bulgarian lev (BGN)', value: 'BGN' },
  { label: 'Czech koruna (CZK)', value: 'CZK' },
  { label: 'Pound sterling (GBP)', value: 'GBP' },
  { label: 'Hungarian forint (HUF)', value: 'HUF' },
  { label: 'Polish zloty (PLN)', value: 'PLN' },
  { label: 'Romanian leu (RON)', value: 'RON' },
  { label: 'Swedish krona (SEK)', value: 'SEK' },
  { label: 'Swiss franc (CHF)', value: 'CHF' },
  { label: 'Icelandic krona (ISK)', value: 'ISK' },
  { label: 'Norwegian krone (NOK)', value: 'NOK' },
  { label: 'Croatian kuna (HRK)', value: 'HRK' },
  { label: 'Russian rouble (RUB)', value: 'RUB' },
  { label: 'Turkish lira (TRY)', value: 'TRY' },
  { label: 'Australian dollar (AUD)', value: 'AUD' },
]
