export const CURRENCIES = [
  { short: 'EUR', name: 'Euro' },
  { short: 'JPY', name: 'Japanese yen' },
  { short: 'BGN', name: 'Bulgarian lev' },
  { short: 'CZK', name: 'Czech koruna' },
  { short: 'GBP', name: 'Pound sterling' },
  { short: 'HUF', name: 'Hungarian forint' },
  { short: 'PLN', name: 'Polish zloty' },
  { short: 'RON', name: 'Romanian leu' },
  { short: 'SEK', name: 'Swedish krona' },
  { short: 'CHF', name: 'Swiss franc' },
  { short: 'ISK', name: 'Icelandic krona' },
  { short: 'NOK', name: 'Norwegian krone' },
  { short: 'HRK', name: 'Croatian kuna' },
  { short: 'RUB', name: 'Russian rouble' },
  { short: 'TRY', name: 'Turkish lira' },
  { short: 'AUD', name: 'Australian dollar' },
]

export const SYMBOL = {
  USD: '$',
  EUR: '€',
  JPY: '¥',
  BGN: 'лв.',
  CZK: 'Kč',
  GBP: '£',
  HUF: 'Ft',
  PLN: 'zł',
  RON: 'L',
  SEK: 'kr',
  CHF: 'Fr',
  ISK: 'kr',
  NOK: 'kr',
  HRK: 'kn',
  RUB: '₽',
  TRY: '₺',
  AUD: 'A$',
}

export const CURRENCY_OPTIONS = [
  { label: 'United States dollar (USD)', value: 'USD' },
  { label: 'Euro (EUR)', value: 'EUR' },
  { label: 'Japanese yen (JPY)', value: 'JPY' },
  { label: 'Bulgarian lev (BGN)', value: 'BGN' },
  { label: 'Czech koruna (CZK)', value: 'CZK' },
  { label: 'Pound sterling (GBP)', value: 'GBP' },
  { label: 'Hungarian forint (HUF)', value: 'HUF' },
  { label: 'Polish zloty (PLN)', value: 'PLN' },
  { label: 'Romanian leu (RON)', value: 'RON' },
  { label: 'Swedish krona (SEK)', value: 'SEK' },
  { label: 'Swiss franc (CHF)', value: 'CHF' },
  { label: 'Icelandic krona (ISK)', value: 'ISK' },
  { label: 'Norwegian krone (NOK)', value: 'NOK' },
  { label: 'Croatian kuna (HRK)', value: 'HRK' },
  { label: 'Russian rouble (RUB)', value: 'RUB' },
  { label: 'Turkish lira (TRY)', value: 'TRY' },
  { label: 'Australian dollar (AUD)', value: 'AUD' },
]

export const CURRENCIES_ARRAY = [
  'EUR',
  'JPY',
  'BGN',
  'CZK',
  'GBP',
  'HUF',
  'PLN',
  'RON',
  'SEK',
  'CHF',
  'ISK',
  'NOK',
  'HRK',
  'RUB',
  'TRY',
  'AUD',
]
